services:
  - type: web
    name: real-water-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn water_delivery_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: water_delivery_app.settings
