services:
  - type: web
    name: real-water-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn water_delivery_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: water_delivery_app.settings
      - key: PYTHON_VERSION
        value: 3.11
