services:
  - type: web
    name: real-water-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn water_delivery_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: water_delivery_app.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
