# Generated by Django 5.1.7 on 2025-03-26 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'monthly')], max_length=20)),
                ('event_date', models.DateField()),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('SKIPPED', 'Skipped'), ('PAUSED', 'Paused')], default='PENDING', max_length=20)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.BooleanField(default=False)),
                ('jug_returns', models.IntegerField(default=0)),
                ('shopify_sub_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
