# Generated by Django 5.1.7 on 2025-03-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jugreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='jug_returns',
        ),
    ]
