# Generated by Django 5.1.7 on 2025-03-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_status_schedule_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shopify_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
